import { useState, useEffect } from 'react';
import axios from 'axios';
import jsPDF from 'jspdf';
import { DownloadIcon, PrinterIcon } from '@heroicons/react/outline';

const ReportCard = () => {
  const [selectedStudent, setSelectedStudent] = useState('');
  const [selectedTerm, setSelectedTerm] = useState('First');
  const [selectedYear, setSelectedYear] = useState(new Date().getFullYear());
  const [marks, setMarks] = useState([]);
  const [studentInfo, setStudentInfo] = useState(null);
  const [loading, setLoading] = useState(false);

  const terms = ['First', 'Second', 'Third'];
  const years = [2023, 2024, 2025];

  useEffect(() => {
    if (selectedStudent) {
      fetchMarks();
    }
  }, [selectedStudent, selectedTerm, selectedYear]);

  const fetchMarks = async () => {
    setLoading(true);
    try {
      const token = localStorage.getItem('token');
      const response = await axios.get(`http://localhost:5000/api/marks/student/${selectedStudent}`, {
        headers: { Authorization: `Bearer ${token}` },
        params: { term: selectedTerm, year: selectedYear }
      });
      setMarks(response.data);
      
      // Fetch student info
      const studentResponse = await axios.get(`http://localhost:5000/api/students`, {
        headers: { Authorization: `Bearer ${token}` }
      });
      const student = studentResponse.data.find(s => s.id === parseInt(selectedStudent));
      setStudentInfo(student);
    } catch (error) {
      console.error('Error fetching marks:', error);
    } finally {
      setLoading(false);
    }
  };

  const calculateGrade = (total) => {
    if (total >= 80) return { grade: 'A', remark: 'Excellent' };
    if (total >= 70) return { grade: 'B', remark: 'Very Good' };
    if (total >= 60) return { grade: 'C', remark: 'Good' };
    if (total >= 50) return { grade: 'D', remark: 'Satisfactory' };
    if (total >= 40) return { grade: 'E', remark: 'Pass' };
    return { grade: 'F', remark: 'Fail' };
  };

  const calculateTotal = () => {
    return marks.reduce((sum, mark) => sum + (mark.total_marks || 0), 0);
  };

  const calculateAverage = () => {
    if (marks.length === 0) return 0;
    return (calculateTotal() / marks.length).toFixed(1);
  };

  const generatePDF = () => {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();
    
    // Header
    doc.setFontSize(20);
    doc.setTextColor(30, 58, 138);
    doc.text('Lycée Bilingue Obessa', pageWidth / 2, 20, { align: 'center' });
    
    doc.setFontSize(12);
    doc.setTextColor(100);
    doc.text('Report Card', pageWidth / 2, 30, { align: 'center' });
    
    // Student Info
    if (studentInfo) {
      doc.setFontSize(10);
      doc.setTextColor(0);
      doc.text(`Student: ${studentInfo.first_name} ${studentInfo.last_name}`, 20, 50);
      doc.text(`Student ID: ${studentInfo.student_id}`, 20, 58);
      doc.text(`Class: ${studentInfo.class_level}`, 20, 66);
      doc.text(`Stream: ${studentInfo.stream}`, 20, 74);
    }
    
    doc.text(`Term: ${selectedTerm} Term`, 120, 50);
    doc.text(`Year: ${selectedYear}`, 120, 58);
    doc.text(`Date: ${new Date().toLocaleDateString()}`, 120, 66);
    
    // Table Header
    let y = 90;
    doc.setFillColor(30, 58, 138);
    doc.rect(20, y, 170, 10, 'F');
    doc.setTextColor(255);
    doc.setFontSize(10);
    doc.text('Subject', 25, y + 7);
    doc.text('Assignments', 70, y + 7);
    doc.text('Mid-Term', 100, y + 7);
    doc.text('Final', 130, y + 7);
    doc.text('Total', 155, y + 7);
    doc.text('Grade', 175, y + 7);
    
    // Table Content
    y += 15;
    doc.setTextColor(0);
    marks.forEach((mark, index) => {
      if (y > 250) {
        doc.addPage();
        y = 20;
      }
      
      const gradeInfo = calculateGrade(mark.total_marks);
      
      doc.text(mark.subject_name || mark.subject_id, 25, y);
      doc.text(mark.assignment_marks?.toString() || '-', 70, y);
      doc.text(mark.mid_term_marks?.toString() || '-', 100, y);
      doc.text(mark.final_marks?.toString() || '-', 130, y);
      doc.text(mark.total_marks?.toString() || '-', 155, y);
      doc.text(gradeInfo.grade, 175, y);
      y += 10;
    });
    
    // Summary
    y += 10;
    doc.setFontSize(12);
    doc.setTextColor(30, 58, 138);
    doc.text('Summary', 20, y);
    y += 10;
    doc.setFontSize(10);
    doc.setTextColor(0);
    doc.text(`Total Marks: ${calculateTotal()}`, 20, y);
    doc.text(`Average: ${calculateAverage()}`, 20, y + 10);
    
    const average = parseFloat(calculateAverage());
    const finalGrade = calculateGrade(average);
    doc.text(`Overall Grade: ${finalGrade.grade} (${finalGrade.remark})`, 20, y + 20);
    
    // Footer
    doc.setFontSize(8);
    doc.setTextColor(100);
    doc.text('Generated by Lycée Bilingue Obessa Management System', pageWidth / 2, 280, { align: 'center' });
    
    doc.save(`report-card-${selectedStudent}-${selectedTerm}-${selectedYear}.pdf`);
  };

  return (
    <div className="min-h-screen bg-gray-50 animate-fadeIn">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
        <h1 className="text-3xl font-bold text-gray-800 mb-8">Report Card Generator</h1>
        
        {/* Controls */}
        <div className="bg-white rounded-xl shadow-md p-6 mb-6">
          <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">Student ID</label>
              <input
                type="text"
                placeholder="Enter Student ID"
                value={selectedStudent}
                onChange={(e) => setSelectedStudent(e.target.value)}
                className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500"
              />
            </div>
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">Term</label>
              <select
                value={selectedTerm}
                onChange={(e) => setSelectedTerm(e.target.value)}
                className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500"
              >
                {terms.map(term => (
                  <option key={term} value={term}>{term} Term</option>
                ))}
              </select>
            </div>
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">Year</label>
              <select
                value={selectedYear}
                onChange={(e) => setSelectedYear(parseInt(e.target.value))}
                className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500"
              >
                {years.map(year => (
                  <option key={year} value={year}>{year}</option>
                ))}
              </select>
            </div>
            <div className="flex items-end">
              <button
                onClick={generatePDF}
                disabled={!selectedStudent || marks.length === 0}
                className="w-full px-4 py-2 bg-blue-800 text-white rounded-lg hover:bg-blue-900 transition-colors disabled:opacity-50 disabled:cursor-not-allowed flex items-center justify-center"
              >
                <DownloadIcon className="h-5 w-5 mr-2" />
                Download PDF
              </button>
            </div>
          </div>
        </div>

        {loading ? (
          <div className="text-center py-12">
            <div className="inline-block animate-spin rounded-full h-12 w-12 border-b-2 border-blue-800"></div>
            <p className="mt-4 text-gray-600">Loading report card...</p>
          </div>
        ) : marks.length > 0 ? (
          <div className="bg-white rounded-xl shadow-md overflow-hidden">
            {/* Report Card Header */}
            <div className="bg-gradient-to-r from-blue-800 to-blue-600 text-white p-6">
              <div className="flex justify-between items-start">
                <div>
                  <h2 className="text-2xl font-bold">Lycée Bilingue Obessa</h2>
                  <p className="text-blue-100">Official Report Card</p>
                </div>
                <div className="text-right">
                  <p className="text-sm text-blue-100">Academic Year</p>
                  <p className="text-xl font-semibold">{selectedYear}</p>
                </div>
              </div>
              
              {studentInfo && (
                <div className="mt-6 grid grid-cols-2 md:grid-cols-4 gap-4">
                  <div>
                    <p className="text-xs text-blue-200">Student Name</p>
                    <p className="font-semibold">{studentInfo.first_name} {studentInfo.last_name}</p>
                  </div>
                  <div>
                    <p className="text-xs text-blue-200">Student ID</p>
                    <p className="font-semibold">{studentInfo.student_id}</p>
                  </div>
                  <div>
                    <p className="text-xs text-blue-200">Class</p>
                    <p className="font-semibold">{studentInfo.class_level}</p>
                  </div>
                  <div>
                    <p className="text-xs text-blue-200">Stream</p>
                    <p className="font-semibold capitalize">{studentInfo.stream}</p>
                  </div>
                </div>
              )}
            </div>

            {/* Marks Table */}
            <div className="p-6">
              <h3 className="text-lg font-semibold text-gray-800 mb-4">{selectedTerm} Term Results</h3>
              <div className="overflow-x-auto">
                <table className="w-full">
                  <thead className="bg-gray-50">
                    <tr>
                      <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase">Subject</th>
                      <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase">Assignments</th>
                      <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase">Mid-Term</th>
                      <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase">Final</th>
                      <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase">Total</th>
                      <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase">Grade</th>
                      <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase">Remark</th>
                    </tr>
                  </thead>
                  <tbody className="divide-y divide-gray-200">
                    {marks.map((mark, index) => {
                      const gradeInfo = calculateGrade(mark.total_marks);
                      return (
                        <tr key={index} className="hover:bg-gray-50">
                          <td className="px-4 py-3 text-sm font-medium text-gray-900">
                            {mark.subject_name}
                          </td>
                          <td className="px-4 py-3 text-sm text-gray-900">
                            {mark.assignment_marks || '-'}
                          </td>
                          <td className="px-4 py-3 text-sm text-gray-900">
                            {mark.mid_term_marks || '-'}
                          </td>
                          <td className="px-4 py-3 text-sm text-gray-900">
                            {mark.final_marks || '-'}
                          </td>
                          <td className="px-4 py-3 text-sm font-semibold text-gray-900">
                            {mark.total_marks || 0}
                          </td>
                          <td className="px-4 py-3">
                            <span className={`px-2 py-1 rounded-full text-xs font-medium ${
                              gradeInfo.grade === 'A' ? 'bg-green-100 text-green-800' :
                              gradeInfo.grade === 'B' ? 'bg-blue-100 text-blue-800' :
                              gradeInfo.grade === 'C' ? 'bg-yellow-100 text-yellow-800' :
                              gradeInfo.grade === 'D' ? 'bg-orange-100 text-orange-800' :
                              'bg-red-100 text-red-800'
                            }`}>
                              {gradeInfo.grade}
                            </span>
                          </td>
                          <td className="px-4 py-3 text-sm text-gray-600">
                            {gradeInfo.remark}
                          </td>
                        </tr>
                      );
                    })}
                  </tbody>
                </table>
              </div>

              {/* Summary */}
              <div className="mt-6 bg-gray-50 rounded-lg p-4">
                <h4 className="font-semibold text-gray-800 mb-3">Performance Summary</h4>
                <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
                  <div>
                    <p className="text-sm text-gray-600">Total Marks</p>
                    <p className="text-2xl font-bold text-blue-800">{calculateTotal()}</p>
                  </div>
                  <div>
                    <p className="text-sm text-gray-600">Average</p>
                    <p className="text-2xl font-bold text-blue-800">{calculateAverage()}</p>
                  </div>
                  <div>
                    <p className="text-sm text-gray-600">Overall Grade</p>
                    <p className="text-2xl font-bold text-amber-600">
                      {calculateGrade(parseFloat(calculateAverage())).grade}
                    </p>
                  </div>
                  <div>
                    <p className="text-sm text-gray-600">Remark</p>
                    <p className="text-lg font-semibold text-gray-800">
                      {calculateGrade(parseFloat(calculateAverage())).remark}
                    </p>
                  </div>
                </div>
              </div>
            </div>

            {/* Footer */}
            <div className="bg-gray-50 px-6 py-4 border-t">
              <div className="flex justify-between items-center">
                <p className="text-sm text-gray-500">
                  Generated on {new Date().toLocaleDateString()}
                </p>
                <div className="flex space-x-2">
                  <button
                    onClick={generatePDF}
                    className="flex items-center px-4 py-2 bg-blue-800 text-white rounded-lg hover:bg-blue-900 transition-colors text-sm"
                  >
                    <DownloadIcon className="h-4 w-4 mr-2" />
                    Download PDF
                  </button>
                  <button
                    onClick={() => window.print()}
                    className="flex items-center px-4 py-2 bg-gray-200 text-gray-800 rounded-lg hover:bg-gray-300 transition-colors text-sm"
                  >
                    <PrinterIcon className="h-4 w-4 mr-2" />
                    Print
                  </button>
                </div>
              </div>
            </div>
          </div>
        ) : (
          <div className="bg-white rounded-xl shadow-md p-12 text-center">
            <p className="text-gray-500">
              {selectedStudent ? 'No marks found for this student in the selected term/year' : 'Enter a Student ID to generate report card'}
            </p>
          </div>
        )}
      </div>
    </div>
  );
};

export default ReportCard;